/**
 * Patch flags are optimization hints generated by the compiler.
 * 补丁标志是编译器生成的优化提示。
 * when a block with dynamicChildren is encountered during diff, the algorithm
 * enters "optimized mode". In this mode, we know that the vdom is produced by
 * a render function generated by the compiler, so the algorithm only needs to
 * handle updates explicitly marked by these patch flags.
 * 当在 diff 期间遇到带有 dynamicChildren 的块时，算法进入“优化模式”。在这种模式下，我们知道 vdom 是由编译器生成的渲染函数生成的，因此算法只需要处理这些补丁标志显式标记的更新。
 *
 * Patch flags can be combined using the | bitwise operator and can be checked
 * using the & operator, e.g.
 * 可以使用 | 组合补丁标志。按位运算符，可以使用 & 运算符进行检查，例如
 *
 * ```js
 * const flag = TEXT | CLASS
 * if (flag & TEXT) { ... }
 * ```
 *
 * Check the `patchElement` function in '../../runtime-core/src/renderer.ts' to see how the
 * flags are handled during diff.
 * 检查 '../../runtime-core/src/renderer.ts' 中的 `patchElement` 函数以查看在 diff 期间如何处理标志。
 */
export const enum PatchFlags {
  /**
   * Indicates an element with dynamic textContent (children fast path)
   * 指示具有动态 textContent 的元素（子快速路径）
   */
  TEXT = 1,

  /**
   * Indicates an element with dynamic class binding.
   * 指示具有动态类绑定的元素。
   */
  CLASS = 1 << 1,

  /**
   * Indicates an element with dynamic style
   * 表示具有动态样式的元素
   * The compiler pre-compiles static string styles into static objects
   * + detects and hoists inline static objects
   * 编译器将静态字符串样式预编译为静态对象 + 检测并提升内联静态对象
   * e.g. `style="color: red"` and `:style="{ color: 'red' }"` both get hoisted
   * as:
   * ```js
   * const style = { color: 'red' }
   * render() { return e('div', { style }) }
   * ```
   */
  STYLE = 1 << 2,

  /**
   * Indicates an element that has non-class/style dynamic props.
   * 指示具有非类/样式动态道具的元素。
   * Can also be on a component that has any dynamic props (includes
   * class/style). when this flag is present, the vnode also has a dynamicProps
   * array that contains the keys of the props that may change so the runtime
   * can diff them faster (without having to worry about removed props)
   * 也可以在具有任何动态道具（包括类/样式）的组件上。当这个标志存在时，vnode 也有一个 dynamicProps 数组，其中包含可能更改的道具的键，因此运行时可以更快地区分它们（不必担心删除的道具）
   */
  PROPS = 1 << 3,

  /**
   * Indicates an element with props with dynamic keys. When keys change, a full
   * diff is always needed to remove the old key. This flag is mutually
   * exclusive with CLASS, STYLE and PROPS.
   * 指示带有带有动态键的道具的元素。当密钥发生变化时，总是需要一个完整的差异来删除旧密钥。该标志与 CLASS、STYLE 和 PROPS 互斥。
   */
  FULL_PROPS = 1 << 4,

  /**
   * Indicates an element with event listeners (which need to be attached
   * during hydration)
   * 表示带有事件监听器的元素（在水合期间需要附加）
   */
  HYDRATE_EVENTS = 1 << 5,

  /**
   * Indicates a fragment whose children order doesn't change.
   * 指示其子顺序不变的片段。
   */
  STABLE_FRAGMENT = 1 << 6,

  /**
   * Indicates a fragment with keyed or partially keyed children
   * 指示带有键控或部分键控子级的片段
   */
  KEYED_FRAGMENT = 1 << 7,

  /**
   * Indicates a fragment with unkeyed children.
   * 指示具有未键控子项的片段。
   */
  UNKEYED_FRAGMENT = 1 << 8,

  /**
   * Indicates an element that only needs non-props patching, e.g. ref or
   * directives (onVnodeXXX hooks). since every patched vnode checks for refs
   * and onVnodeXXX hooks, it simply marks the vnode so that a parent block
   * will track it.
   * 表示只需要非道具修补的元素，例如ref 或指令（onVnodeXXX 挂钩）。由于每个修补的 vnode 都会检查 refs 和 onVnodeXXX 钩子，它只是标记 vnode，以便父块跟踪它。
   */
  NEED_PATCH = 1 << 9,

  /**
   * Indicates a component with dynamic slots (e.g. slot that references a v-for
   * iterated value, or dynamic slot names).
   * 表示具有动态插槽的组件（例如，引用 v-for 迭代值的插槽或动态插槽名称）。
   * Components with this flag are always force updated.
   * 带有这个标志的组件总是被强制更新
   */
  DYNAMIC_SLOTS = 1 << 10,

  /**
   * Indicates a fragment that was created only because the user has placed
   * comments at the root level of a template. This is a dev-only flag since
   * comments are stripped in production.
   * 表示仅因为用户在模板的根级别放置评论而创建的片段。这是一个仅限开发人员的标志，因为注释在生产中被剥离。
   */
  DEV_ROOT_FRAGMENT = 1 << 11,

  /**
   * SPECIAL FLAGS -------------------------------------------------------------
   * Special flags are negative integers. They are never matched against using
   * bitwise operators (bitwise matching should only happen in branches where
   * patchFlag > 0), and are mutually exclusive. When checking for a special
   * flag, simply check patchFlag === FLAG.
   * 特殊标志是负整数。它们永远不会使用按位运算符进行匹配（按位匹配应该只发生在 patchFlag > 0 的分支中），并且是互斥的。检查特殊标志时，只需检查 patchFlag === FLAG。
   */

  /**
   * Indicates a hoisted static vnode. This is a hint for hydration to skip
   * the entire sub tree since static content never needs to be updated.
   * 表示已提升的静态 vnode。这是一个提示水合作用跳过整个子树，因为静态内容永远不需要更新。
   */
  HOISTED = -1,
  /**
   * A special flag that indicates that the diffing algorithm should bail out
   * of optimized mode. For example, on block fragments created by renderSlot()
   * when encountering non-compiler generated slots (i.e. manually written
   * render functions, which should always be fully diffed)
   * OR manually cloneVNodes
   * 一个特殊标志，指示差异算法应该退出优化模式。例如，在遇到非编译器生成的插槽时由 renderSlot() 创建的块片段（即手动编写的渲染函数，应该始终完全区分）或手动克隆VNodes
   */
  BAIL = -2
}

/**
 * dev only flag -> name mapping
 */
export const PatchFlagNames = {
  [PatchFlags.TEXT]: `TEXT`,
  [PatchFlags.CLASS]: `CLASS`,
  [PatchFlags.STYLE]: `STYLE`,
  [PatchFlags.PROPS]: `PROPS`,
  [PatchFlags.FULL_PROPS]: `FULL_PROPS`,
  [PatchFlags.HYDRATE_EVENTS]: `HYDRATE_EVENTS`,
  [PatchFlags.STABLE_FRAGMENT]: `STABLE_FRAGMENT`,
  [PatchFlags.KEYED_FRAGMENT]: `KEYED_FRAGMENT`,
  [PatchFlags.UNKEYED_FRAGMENT]: `UNKEYED_FRAGMENT`,
  [PatchFlags.NEED_PATCH]: `NEED_PATCH`,
  [PatchFlags.DYNAMIC_SLOTS]: `DYNAMIC_SLOTS`,
  [PatchFlags.DEV_ROOT_FRAGMENT]: `DEV_ROOT_FRAGMENT`,
  [PatchFlags.HOISTED]: `HOISTED`,
  [PatchFlags.BAIL]: `BAIL`
}
